### ISSUE TITLE
Semantiek HTML

### ISSUE THREAD

**Issue by Anna-Kyra** [Einanas/the-startup-S6#10]
Je kan de HTML nog semantischer maken om `<main>` te gebruiken voor je main content en `<footer>` gebruiken voor de eventuele footer. Had al gezien dat je `<header>` gebruikte

**Comment by Pink-Mallow** [comment]
Yesss! Ik heb de main toe gepast voor de content en ik merkte meteen een verschil. Het opmaakt ging makkelijker. Ik zal nog kijken of ik de ```<footer>``` ga toevoegen. Maar ik waardeer de tip 😊
