### ISSUE TITLE
Unclosed element path.

### ISSUE THREAD

**Issue by Akikosophia** [Einanas/the-startup-S6#12]
De path moet  gesloten worden :)

<img width="1297" alt="Scherm­afbeelding 2024-01-22 om 07 33 32" src="https://github.com/Einanas/the-startup-S6/assets/144008863/6323cf4e-e0fa-42bc-8b2e-be169614e50f">

Op deze regel kun je hem aanpassen!

https://github.com/Einanas/the-startup-S6/blob/a6c3a1495c5bc493eee5b5d4a6439047f806a9fb/index.html#L51

**Comment by Pink-Mallow** [comment]
Ik heb het gesloten! Ik had het niet gezien omdat het ver rechts van de pagina zit. Goed dat je het hebt benoemd 😭
