### ISSUE TITLE
Menu en navigaitie

### ISSUE THREAD

**Issue by Ronabundy1** [Einanas/the-startup-S6#13]
Het lijkt erop dat je het menu- en navigatiegedeelte hebt uitgeschakeld. Als je van plan bent om ze te gebruiken, verwijder dan de opmerkingstekens en pas ze aan zoals nodig.

**Comment by Pink-Mallow** [comment]
Zal ik zeker doen! Ik heb het gedaan zodat ik mezelf niet zou afleiden en alleen op 1 ding kan focussen.
