### ISSUE TITLE
Correcte alt attributen voor afbeeldingen

### ISSUE THREAD

**Issue by Ronabundy1** [Einanas/the-startup-S6#14]
Zorg ervoor dat de alt-attributen voor afbeeldingen zinvol en beschrijvend zijn. Ze helpen bij toegankelijkheid.

**Comment by Pink-Mallow** [comment]
Ik heb het meteen aangepast. Ik hoop dat ze nu zinvol en beschrijvend zijn! Ik waardeer het advies.
