### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by Hadil66** [Einanas/the-startup-S6#2]
Let op de spacing. Er is veel spatie waardoor het niet zo netjes lijkt.

https://github.com/Einanas/the-startup-S6/blob/d9e1fa8c56c8e6dc5bf3dde1579dfffdb5febae2/index.html#L73-L77

**Comment by Pink-Mallow** [comment]
Ik heb de codes aangepast en heb beter nagedacht waar ik de spacing doe om het wat netter te laten lijken. Maar soms lijkt het overbodig omdat ik het voor mezelf zo doe om meteen naar de code te gaan zodat ik weet wat ik moet aanpassen als ik bezig ben met de css. Het is een goede tip en zal proberen voortaan erop te letten.
