### ISSUE TITLE
Div gebruik

### ISSUE THREAD

**Issue by lisavanmansom** [Einanas/the-startup-S6#3]
je gebruikt aardig wat div's hierdoor is het minder overzichtelijk voor andere in je code is als die aan het kijken zijn. Ook is het niet super semantisch. Je kan bijvoorbeeld inplaats van div's, articles gebruiken

**Comment by Pink-Mallow** [comment]
Heb ik toegepast!!! Het was inderdaad niet semantisch en ik begon heel slordig. Ik heb de tip toegepast en ik zal proberen meer te variëren in de codes om het semantischer te maken.
