### ISSUE TITLE
Img class

### ISSUE THREAD

**Issue by Hadil66** [Einanas/the-startup-S6#4]
In plaats van images in een div te zetten en een class te geven kan je img class=" " gebruiken of om het te selecteren img:nth-of-type().

https://github.com/Einanas/the-startup-S6/blob/d9e1fa8c56c8e6dc5bf3dde1579dfffdb5febae2/index.html#L88-L90C19

**Comment by Pink-Mallow** [comment]
Is een hele slimme tip. Ik heb er totaal niet aan gedacht. Ik heb uiteindelijk iets anders gedaan met de images maar ik heb die techniek wel toe gepast op een andere soort code,  de ```<span>``` tag.
