### ISSUE TITLE
euhm wat gebeurd er hier?

### ISSUE THREAD

**Issue by KaanKalmi** [Einanas/the-startup-S6#5]
![image](https://github.com/Einanas/the-startup-S6/assets/144000125/2bcdf39f-3547-4552-8205-de723ec62437)

Dit hoort niet zo te zijn of wel?

**Comment by Pink-Mallow** [comment]
Nope, maar ik heb iets anders gedaan wat er beter uit ziet. Alleen de javascript werkt niet dus ik moet dat aanpassen 🙃 . Het is nu niet te zien omdat ik het even op comment heb gezet (als ik het goed zeg).
