### ISSUE TITLE
Zelfde alt tag 

### ISSUE THREAD

**Issue by RukiyaTossou** [Einanas/the-startup-S6#9]
- https://github.com/Einanas/the-startup-S6/blob/f5fe3d203d37efa7868e26a3b7f5ef975c12ea3b/index.html#L99-L112
- Je hebt bij meerdere afbeeldingen dezelfde alt tag 
- Probeer  een minder algemene beschrijving te geven.

**Comment by Pink-Mallow** [comment]
Ik zal het meteen fixen. Het is inderdaad niet handig voor screen readers. Goed dat je het hebt benoemd ✨
